environments:
  dev:
    apiBaseUrl: https://adams-dev-api.tataplay.com
    gitBranches:
      ad-management-service: develop
      campaign-management-service: develop
  uat:
    apiBaseUrl: https://adams-uat-api.tataplay.com
    gitBranches:
      ad-management-service: release/uat
      campaign-management-service: release/uat
  prod:
    apiBaseUrl: https://adams-api.tataplay.com
    gitBranches:
      ad-management-service: main
      campaign-management-service: main
