environments:
  dev:
    apiBaseUrl: https://adams-dev-api.tataplay.com
    gitBranches:
      ad-management-service: dev
      campaign-management-service: dev
  uat:
    apiBaseUrl: https://adams-uat-api.tataplay.com
    gitBranches:
      ad-management-service: uat
      campaign-management-service: uat
  prod:
    apiBaseUrl: https://adams-api.tataplay.com
    gitBranches:
      ad-management-service: prod
      campaign-management-service: prod
